lirantal/daloradius

gis-main.php
gis-viewmap.php
library/googlemaps.php

GIS mapping has an error when trying to use the Google Maps API when DaloRADIUS is under HTTPS.
It also has issues with using version 2 of the API, changing this to version 3 seems to work.
- Change script to use a URL without a scheme
- Change images to use URLs without a scheme
- Change Google Maps API to v=3

fix: Maps Error When Using HTTPS

---

library/exten-boot_log.php
library/exten-daloradius_log.php
library/exten-radius_log.php
library/exten-syslog_log.php

- This function was deprecated in PHP 5.3.0, and removed in PHP 7.0.0.
- http://php.net/manual/en/function.eregi-replace.php
- Replace instances of `eregi_replace` with `preg_replace`
There is another instance where git thinks the entire file changed, I wonder if line endings are changing for some reason.

fix: eregi_replace is deprecated in PHP5.3, removed in PHP7

---

Dockerfile

Solution from
https://serverfault.com/questions/870568/fatal-error-cant-open-and-lock-privilege-tables-table-storage-engine-for-use
MySQL were crashing preventing the socket to be open

Fixed MySQLd permission issue

---

mng-del.php

Line 157
which is
list($userSessions,$acctStartTime) = preg_split('\|\|', $value);
should be
list($userSessions,$acctStartTime) = preg_split('/\\|\\|/', $value);

A clearSessionsUsers BUG in mng-del.php

---

library/exten-server_info.php

This doesn't resolve the deprecation of ifconfig in favour of ip, but at least that only requires the installation of net-tools :)

Fix ifconfig parsing for later versions of net-tools/ifconfig

---

include/management/autocomplete.php
mng-batch-add.php
mng-batch-list.php
mng-edit.php
mng-new.php
mng-rad-groupcheck-new.php
mng-rad-groupreply-new.php
mng-rad-profiles-edit.php
mng-rad-profiles-new.php

It includes:
- Initialize DHTML Suite "properly" to let it load the file `auto-complete.css` by itself, avoiding load errors. _(1)_
- Delete direct links to the file `auto-complete.css`.
_(1)_
[DHTML Suite](http://www.dhtmlgoodies.com/index.html?dhtml-suite-page=dhtmlSuite-configuration-variables)
> Themes
> Which theme to use in the DHTML Suite is controlled by a variable named DHTML_SUITE_THEME. The default value of this variable is "blue". This value will always correspond with the name of one of the sub folders inside the "themes" folder:
> 
> Example: "blue", "gray" or "light-cyan".
> 
> If you want to use a different theme, you need to change this variable before creating any DHTMLSuite objects.
> 
> Path to the "themes" folder
> The DHTML_SUITE_THEME_FOLDER variable is used to …

Autocomplete fix

---

daloradius-users/include/management/pages_common.php
include/management/pages_common.php

Use:
`<a href="#" onclick="javascript:func();return false;">...</a>`
instead of:
`<a href="javascript:return;" onclick="javascript:func();>...</a>`

Right use of href and onclick attributes in <a> tags in tooltips.

---

acct-active.php
acct-all.php
acct-date.php
acct-hotspot-accounting.php
acct-ipaddress.php
acct-nasipaddress.php
acct-plans-usage.php
acct-username.php
bill-plans-list.php
bill-pos-list.php
mng-batch-list.php
mng-hs-list.php
mng-rad-attributes-list.php
mng-rad-attributes-search.php
mng-search.php
rep-batch-details.php
rep-batch-list.php

That's the reason I don't like to include $vars inside double-quoted strings.
Before, it was:
`"<a>$l['name']</a>"`
After the changes in translation procedure now it is - wrong:
`"<a>t('name')</a>"`
This PR converts it to:
`"<a>".t('name')."</a>"`

Right use of translation function inside double-quoted strings.

---

library/exten-daloradius_log.php

Just that, a closing bracket was missing.

Missing closing bracket.

---

rep-lastconnect.php

Possibly a fix for #58.
Potential bug in `rep-lastconnect.php` if we are running daloRADIUS under FreeRadius 3 and we have set `$configValues['FREERADIUS_VERSION']` to the value `'3'`:
```
if (isset($configValues['FREERADIUS_VERSION']) && ($configValues['FREERADIUS_VERSION'] == '2')) {
$tableSetting['postauth']['user'] = 'username';
$tableSetting['postauth']['date'] = 'authdate';
} elseif (isset($configValues['FREERADIUS_VERSION']) && ($configValues['FREERADIUS_VERSION'] == '1')) {
$tableSetting['postauth']['user'] = 'user';
$tableSetting['postauth']['date'] = 'date';
}
```
If that is the case, both `$tableSetting['postauth']['user']` and `$tableSetting['postauth']['date']` will be undefined, so the SQL queries would be bad formed:
```
$sql = "SELECT ". …
```

Fix SQL query for last connection attempts where FreeRADIUS is v3.

---

bill-pos-edit.php
bill-pos-new.php
mng-batch-add.php
mng-edit.php
mng-new.php

A workaround to fix SQL syntax errors when running any queries that involve using the column 'lead', as it is a reserved word in MySQL 8.0.2+
Check: https://dev.mysql.com/doc/refman/8.0/en/keywords.html

Fix SQL syntax errors when using the column 'lead' with MySQL 8.0.2+

---

ChangeLog
README.md
daloradius-users/library/tableConventions.php
lang/en.php
lang/ja.php
lang/zh.php
library/daloradius.conf.php
library/tableConventions.php
mng-batch-del.php
mng-del.php
rep-lastconnect.php

Set right column names for table radpostauth in FreeRADIUS v3, plus syntax fix in language translations.
Fixes issue #44.

Set right column names for table radpostauth in FreeRADIUS v3 plus language fixes.

---

Dockerfile-freeradius

I improved the Dockerfile a bit. Some cosmetics, some Dockerfile best practices. I added net-tools for the Server-Status page. I also added pear Mail and Maile-Mime as suggested in the requirements. I deleted the explicit Ubuntu mirrors to let Ubuntu choose it's own download location.
Maybe it's also time to switch to Ubtunu 18.04? My own Daloradius Docker image works fine with it.
The Dockerfile does build and start fine.

Some Dockerfile improvements

---

library/exten-maint-radclient.php

fix Error parsing "stdin" on radclient test in case of User-Password empty

fix Error parsing "stdin" on radclient test

---

ChangeLog
README.md
mng-new.php

Fix:
> PR #164 
> ISSUE #191
> ISSUE #166
Requires PHP v5.5 or higher.

Fix MAC validation in new user (requires PHP v5.5).

---

mng-rad-ippool-del.php

This fixed the reg expression and a possible variable conflict with the variable $poolname.
It also corrects an issue where only the last ip in the list was displayed as deleted.   The new behavior is to list all ips that were removed from the database.

Suggestion to correct issue with not deleting ips from pool when selected is ippool list

---

mng-rad-hunt-del.php

fix preg_split function regular expression for correctly detect || between nasipaddress and portid

---

Dockerfile

If daloradius.conf.php does not exists you will get permission errors since the file in the init.sh file is created as root.

Make sure daloradius.conf.php exists

---

dologin.php
library/daloradius.conf.php.sample
library/opendb.php

This PR fixes #248.
The previous code failed to read the db configuration for a given location.
Also it failed to select the db port in case it was not set.
Now it's compulsory to set the db port for each location in the configuration file, in order to be consistent with the default configuration.
The configuration sample file has been modified to reflect this change:
```
// Locations Configuration directives
// Locations directives are support for accessing different databases from the daloRADIUS Login console
// adjust the locations below for databases you are running (if you are running more than one).
// You could configure invoice templates for each location - optional.
$configValues['CONFIG_LOCATIONS'] = array(
"Location Example 1" => array(
"Engine"   => "mysql",
"Username" => …
```

Fix support for multiple db locations.

---

mng-batch-add.php

On batch user add the radusergroup table expects four values as the fields aren't explicitly declared in the INSERT statement. This causes an error on INSERT, this patch adds the ID field as NULL (it will auto-increment regardless of the value being declared as NULL)

Quick fix for batch user add error

---

library/sessions.php

I have fixed an incompatibility error with PHP versions < 5.6.0 (when handling sessions), which do not have hash_equals function.

fixed incompatibility error with php < 5.6.0 when handling sessions

---

Dockerfile
Dockerfile-freeradius
app/operators/config-maint-test-user.php
app/operators/mng-del.php
app/operators/mng-new-quick.php
docker-compose.yml
init-freeradius.sh
init.sh

Tweaks for docker:
- password length fields from environment into config
- radius port to test against
- consistent file location for lockfile, /data instead of mix of /data + /internal_data
- init script startup now catches empty config files and regenerates
Fixing user attribute delete problem with clobbering of @ in usernames making the SQL fail.
Create user wizard now has awareness of which fields are Check vs Reply
Fixes for user test, 3 x if statements previously were checking if there was radius config, and if there was, ignore it and use defaults instead; now correctly uses the config if it's found.  Also populates password boxes if it's come through from the user page

Handful of fixes

---

init.sh

The init.sh script refers to a non-extant file to do initial population of the database.

Update database init to point to correct script

---

app/operators/acct-maintenance-delete.php

The current DELETE query does not remove entries until the end of the specified date, as it only matches entries within the range. This PR modifies the SQL query by adding one day to the end date to ensure it matches and deletes all entries up to and including the specified date.

fix/acct-maintenance-delete: delete records in specific day

---

init-freeradius.sh

if any params in the mysql TLS config is set then tls is enabled. This fixes the issue
https://github.com/FreeRADIUS/freeradius-server/blob/d864ca7c176c0c1ab8b0fda6cdacb5edea774f40/src/modules/rlm_sql/drivers/rlm_sql_mysql/rlm_sql_mysql.c#L287

fix: Disable TLS for mysql

---

app/operators/mng-rad-nas-list.php

Fix for issue [#590](https://github.com/lirantal/daloradius/issues/590#issue-2763955516) and issue [#572](https://github.com/lirantal/daloradius/issues/572#issue-2582569653).  Cannot delete NAS.

Fix CSRF token validation in NAS deletion operation

---

app/operators/library/checklogin.php

count slashes **after** the first in the URL when calculating where "login.php" is, so that daloradius does not redirect to ../login.php for every request except login.php

Make daloradius admin work in a sub-directory
