lirantal/daloradius

- library/daloradius.conf.php
- library/opendb.php
> Adding support for PHP7

- bill-rates-date.php
- bill-rates-edit.php
- config-backup-managebackups.php
- contrib/chilli/portal2/signup-2checkout/2co_ipn.php
- include/common/printTickets.php
- include/management/userBilling.php
- library/exten-server_info.php
- mng-del.php
- mng-edit.php
- mng-rad-attributes-del.php
- mng-rad-attributes-import.php
- mng-rad-groupcheck-del.php
- mng-rad-groupreply-del.php
- mng-rad-hunt-del.php
- mng-rad-ippool-del.php
- mng-rad-profiles-del.php
- mng-rad-profiles-edit.php
- mng-rad-usergroup-del.php
Replacing deprecated split function in PHP7 with explode() or preg_split()
Fixes #5
> Replacing deprecated split function

- Dockerfile
- init.sh
First official and initial support for daloRADIUS as a docker container
> Enabling docker support for daloradius

- library/exten-daloradius_log.php
- library/exten-radius_log.php
A partial solution to issue https://github.com/lirantal/daloradius/issues/23
> Properly display Radius and DaloRADIUS logs

- daloradius-users/library/daloradius.conf.php
- daloradius-users/library/opendb.php
- daloradius-users/library/tableConventions.php
> daloradius-users/ directory missing same fixes applied to daloradius/ dir

- .gitignore
- bill-invoice-edit.php
- bill-invoice-list.php
- bill-payments-list.php
- css/1.css
- doc/billing.md
- include/common/notificationsUserInvoice.php
- library/daloradius.conf.php
- notifications/processNotificationUserInvoice.php
- notifications/templates/invoice_item_template.html
- notifications/templates/invoice_template.html
New billing style for Daloradius.
Its use it's optional, and one can still using the traditional style or change to the new style, or revert, at any time.
It lets you use a lot of new fields for the design and cutomization of your invoices.
It use two HTML templates: one for the invoice body, and another for the invoice items.
> New billing style.

- init.sh
Added mysql dirs chown
Removed the &>/dev/null
> Permission check mysql

- INSTALL
- INSTALL.openSUSE
- INSTALL.quick
- INSTALL.win
- README.md
- daloradius-users/lang/en.php
- daloradius-users/lang/ro.php
- daloradius-users/lang/ru.php
- daloradius-users/menu-home.php
- lang/en.php
- lang/es_VE.php
- lang/hu.php
- lang/it.php
- lang/ja.php
- lang/pt_br.php
- lang/ro.php
- lang/ru.php
- lang/zh.php
- menu-help.php
- menu-home.php
- update.php
> Change project website url, email address, copyright notes to Liran Tal.

- acct-maintenance-cleanup.php
- include/management/buttons.php
- lang/en.php
Cleanup stale sessions by username, closing opened sessions in FreeRADIUS database.
It helps to solve the issue #84
> Add cleanup (close) stale sessions by username.

- config-maint-disconnect-user.php
Just that: remove some useless JS code that was causing an error in the browser.
> Delete useless code causing JS error.

- ChangeLog
- README.md
- daloradius-users/lang/en.php
- daloradius-users/lang/ro.php
- daloradius-users/lang/ru.php
- daloradius-users/library/daloradius.conf.php
- lang/en.php
- lang/es_VE.php
- lang/hu.php
- lang/it.php
- lang/ja.php
- lang/pt_br.php
- lang/ro.php
- lang/ru.php
- lang/zh.php
- library/daloradius.conf.php
Change version number to 1.0-0 according to PR #89
> Change version number to 1.0-0

- library/daloradius.conf.php
- mng-rad-profiles-new.php
Fix for #95 when target value is empty when adding profiles.
> Show error message on missing target value when adding profiles.

- Dockerfile
User connectivity test was not working
> Added freeradius-utils and cron to dockerfile

- login.php
Remove "Default" location if multiple locations are set
> Remove "Default" location if multiple locations are set

- README.md
Add contributors listing to the top of the README to further recognise these wonderful people for their   time and effort to this project ❤️
> chore: add contributors list to the README

- ChangeLog
- README.md
- css/1.css
- include/management/populate_selectbox.php
- lang/en.php
- lang/es_VE.php
- lang/hu.php
- lang/it.php
- lang/ja.php
- lang/pt_br.php
- lang/ro.php
- lang/ru.php
- lang/zh.php
- library/daloradius.conf.php
- mng-batch-add.php
Fix for #112 and a bit more:
- add select box for password types in Batch Add Users option
- stylish ToolTip boxes
- update changelog
- release v1.1-0
> Add select box for password types in Batch Add Users option and a bit more

- Dockerfile-freeradius
- init-freeradius.sh
Create new Dockerfile-freeradius and init-freeradius.sh
> Dockerfile-freeradius + init-freeradius.sh

- lang/pt_br.php
Greetings I liked the software, I am translating I am already on line 796 I would like to donate to the community I intend to end this weekend
> update language line 796

- ChangeLog
- library/daloradius.conf.php
ChangeLog.
Change version to 1.1-3 BETA for now.
> Reflect last changes

- ChangeLog
- include/management/userReports.php
- library/daloradius.conf.php
> Remove unavailable data in SUBSCRIPTION ANALYSIS view.

- include/management/populate_selectbox.php
- menu-mng-batch.php
> Fix new batch users issues.

- mng-new.php
Validate A MAC Address and strip separator
> Validate A MAC Address and strip separator

- daloradius-users/notifications/dompdf/dompdf_config.inc.php
Fixes #204 (https://github.com/lirantal/daloradius/issues/204)
> fix: resolve security issue that allows PHP in templates

- notifications/dompdf/dompdf_config.inc.php
Fixes #204 (https://github.com/lirantal/daloradius/issues/204)
> fix: security issue defaulting to exec php in templates

- Dockerfile
> also logging files should be added

- dologin.php
- library/opendb.php
- library/sessions.php
- login.php
1) HttpOnly flag on session cookie
2) csrf_token protection on login form
> Added some security features

- include/management/fileExport.php
- library/graphs-reports-new-users.php
- library/graphs-reports-online-nas.php
- library/graphs-reports-online-users.php
- mng-list-all.php
- mng-search.php
- rep-history.php
- rep-lastconnect.php
- rep-newusers.php
- rep-online.php
- rep-topusers.php
Corrected some query.
Improved param validation and UI.
> Improved user reports section.

- library/chart-mng-total-users.php
- library/graphs-alltime-traffic-download.php
- library/graphs-alltime-traffic-upload.php
- library/graphs-alltime-users-login.php
- library/graphs-hotspot-compare-hits.php
- library/graphs-hotspot-compare-time.php
- library/graphs-hotspot-compare-unique-users.php
- library/graphs-overall-users-download.php
- library/graphs-overall-users-login.php
- library/graphs-overall-users-upload.php
- library/graphs-reports-new-users.php
- library/graphs-reports-online-nas.php
- library/graphs-reports-online-users.php
I have standardized the way we used for passing labels and values to libchart Point constructor and addPoint function.
This way we have the full control on value types (string and integer) passed to constructor and function.
> Standardized way of passing labels and values to libchart

- acct-custom-query.php
- acct-custom.php
- acct-plans-usage.php
- acct-plans.php
- config-operators-edit.php
- config-operators-new.php
- library/layout.php
- library/validation.php
- menu-accounting-custom.php
- menu-accounting-plans.php
- menu-accounting.php
- menu-bill-history.php
- menu-bill-invoice.php
- menu-bill-merchant.php
- menu-bill-paypal.php
- menu-bill-rates.php
- menu-billing.php
- menu-graphs.php
- menu-reports.php
- mng-hs-edit.php
- mng-hs-new.php
- mng-rad-nas-new.php
Started replacing old datepicker library with new HTML native input type="date" component.
Also I have fixed some issues in loading CSS styles in some pages, which could be related to reported issue #279
> Started replacing old datepicker library with new HTML native input type="date" component

- include/management/functions.php
otherwise function is not writing to radusergroup and mng-batch-add is failing
> Typo when renamed function arguments

- acct-active.php
- acct-all.php
- acct-date.php
- acct-ipaddress.php
- acct-nasipaddress.php
- acct-username.php
- bill-rates-date.php
- gis-editmap.php
- heartbeat.php
- include/management/buttons.php
- include/management/functions.php
- include/management/groups.php
- include/management/userReports.php
- library/attributes.php
- library/validation.php
- mng-edit.php
- mng-rad-hunt-list.php
- rep-hb-dashboard.php
- rep-lastconnect.php
- rep-topusers.php
- rep-username.php
Addressed reported issues on hunt-groups, acct and mng-edit.
Also, improved heartbeat and other features.
> Addressed reported issues

- lang/tr.php
- library/validation.php
Finalizing turkish language support
> Introduced turkish language support

- contrib/heartbeat/dalo-dashboard-update-openwrt.sh
sh script for Openwrt devices running chilli with daloradius dashboard
> adding openwrt heartbeat script

- library/layout.php
- mng-rad-nas-new.php
Variable reference change on function print_select on layout.php
Link reference update on mng-rad-nas-new.php
> update on some references

- contrib/heartbeat/dalo-dashboard-update-openwrt.sh
Updating NAS_MAC value to extract MAC from uci get chilli.chilli1.radiusnasid
> Updating NAS_MAC value

- .gitignore
- Dockerfile
- contrib/docker/operators.conf
- contrib/docker/users.conf
- docker-compose.yml
- init.sh
This gets docker back up and running again for the 2.0 beta, and can be tested with the very slightly adjusted docker-compose.
Addresses #236 & #406
> Dockerfile for 2.0beta 

- Dockerfile-standalone
- README.docker-standalone.md
- contrib/scripts/apache-config.sh
- docker-compose.yml
Now final image will contain Daloradius (master branch) with apache configs enabled for Operators portal (port 8000) and Users portal (port 80).
> Make Docker-standalone really standalone

- app/operators/mng-new-quick.php
> fix: max all session on quick user add

- app/operators/bill-plans-new.php
This will fix #493 
just add empty argument to end of method sprintf.
please let me know if any concern.
> FIX: missing argument

- app/operators/library/extensions/maintenance_radclient.php
> Fix: update radclient user auth command

- app/operators/mng-search.php
> Add search condition for radreply table for search IP in mng-search.php

- README.md
- app/common/includes/layout.php
- app/common/includes/validation.php
- app/common/includes/version.php
- app/operators/acct-active.php
- app/operators/acct-all.php
- app/operators/acct-custom-query.php
- app/operators/acct-custom.php
- app/operators/acct-date.php
- app/operators/acct-hotspot-accounting.php
- app/operators/acct-ipaddress.php
- app/operators/acct-nasipaddress.php
- app/operators/acct-username.php
- app/operators/include/management/functions.php
- app/operators/include/management/pages_common.php
- app/operators/include/management/pages_numbering.php
- app/operators/include/menu/sidebar/acct/custom.php
- app/operators/lang/en.php
- app/operators/mng-del.php
- app/operators/mng-rad-attributes-search.php
Through the custom accounting section, IPv6 related fields (mainly contained in the radacct table) are taken into account.
> Improved accounting features and minor fixes

- app/common/includes/daloradius.conf.php.sample
- app/common/static/js/pages_common.js
- app/operators/library/ajax/user_actions.php
- app/operators/mng-list-all.php
- app/operators/mng-search.php
In my organization, there was a need to add the capability for bulk sending of usernames and passwords to users. 
I’ve implemented the required functionality. 
Hopefully, this will be useful for others as well.
> Add functionality to send login credentials via email

- app/operators/mng-new-quick.php
fix quick add format to default dd MMM YYYY
> feat: format expiration date to d M Y in new quick management

- app/operators/bill-pos-del.php
- app/operators/bill-pos-new.php
fix: Improve handling of numeric values for plan costs and taxes in billing operations
> fix: Improve handling of numeric values for plan costs and taxes in billing operations
